### ISSUE TITLE
Embedding ZWave-JS-UI

### ISSUE THREAD

**Issue by tofbouf** [YunoHost-Apps/domoticz_ynh#10]
Since the OpenZWave module is tagged as obsolete in Domoticz, it would be great if the Yunohost package for Domoticz could also embed the replacement for OpenZWave, ie. Zwave-JS-UI (https://www.domoticz.com/wiki/Zwave-JS-UI), just like it does for Mosquitto.

**Comment by Krakinou** [comment]
Indeed.
I'm still trying to understand how it should work, but I plan to release something in the future.
When I look at the domoticz forums, it seems that many people are fighting to get it working, wiki instruction for installing and setting up the config is not very clear yet, etc., so I may wait a little while so that things settle down before working on it.

Anyway, I myself use a lot of zwave device so sooner or later I will have to do the move :)

**Comment by Krakinou** [comment]
FYI, work has started [here](https://github.com/YunoHost-Apps/zwave-js-ui_ynh)
And this is a pain in the a**! Expect a few weeks/month before this works

I will close this issue when ready

**Comment by tofbouf** [comment]
No problem, personally, I stopped at "install with docker" :-)
Thanks for the interest in this package.

**Comment by Krakinou** [comment]
Done in a new package [here](https://github.com/YunoHost-Apps/zwave-js-ui_ynh/tree/master).
Should be available in the catalog shortly
